var Projects = [];
Projects[0] = '';
Projects[1] = '{"Project_Name":"Employee Training System","Duration":"3 Months","Technology":"ASP.NET MVC , C#, Entity Framework, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["System is designed for Training for employees","System automatically generate existing users credentials","Employee able to login and start learning (watch videos ) for training","After completion of this learning (watch videos) employee able to proceed for test","Completion on test system automatically calculate the marks and present to employee","Admin can view the Employee progress from admin section","Admin can able to add new Questions","Admin can able to delete existing user","Admin can able to add new videos"],"URL":"","PictureCount":17,"PictureFolderName":"TrainingApp"}';
Projects[2] = '{"Project_Name":"Secure English Language Teaching System","Duration":"1 Year","Technology":"Asp.net , C#, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["To make different from all teaching systems","Convert Paper base learning to online learning system","Introducing online writing pad for drawing objects","Online tutoring supports","Online Tutor Portal","Tutor able to check students attempted tests ","Online Partner portal ","Partner able to refer students","Partner able to view student progress","Partner able to view their earning details","Online Admin Control Panel","Admin able to add or remove students, partner, tutors ","Admin able to add new course","Admin able to create new schedule","Admin able to add new Modules, Question Types, Question, Passages","Admin able to change the front screen contents","Admin able to create email templates","Admin able to see student feedback ","Admin able to create events"],"URL":"www.cies.edu.pt","PictureCount":61,"PictureFolderName":"SELTS"}';
Projects[3] = '{"Project_Name":"Payment Deposit","Duration":"1 Month","Technology":"ASP.NET MVC , C#, Entity Framework, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["Purpose of this application to track the deposited payments","Tracking the non-invoicing payments","Tracking the Checks (Payments)","Track the deposited checks","In reporting export in PDF format"],"URL":"","PictureCount":2,"PictureFolderName":"XPI"}';
Projects[4] = '{"Project_Name":"Employee Points Calculation","Duration":"2 Month","Technology":"ASP.NET MVC , C#, Entity Framework, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["System is designed for calculation the employee point those are customers provided",null,"System able to calculate monthly details in each category (Breakage, Teamwork, Attendance, Complaint, Compliment, Protocol, Feedback and customer lost)","Calculate total employee points","Check Employee Counseling details","Searching criteria in different point of view "],"URL":"","PictureCount":4,"PictureFolderName":"OMSS"}';
Projects[5] = '{"Project_Name":"Hafiz Noor Quran Academy","Duration":"3 Months","Technology":"Asp.net , C#, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["To provide online Quran teaching system over the world","Any type of person who want to read, understand Quran and translation, schedule their learning period","Facilitate to every Muslims to learn Quran anywhere","Thelp the souls who desire to be enlightened with the blessing of Holy Quran across the boundaries of countries and oceans and to enhance their knowledge about Quran, by delivering best distance learning Quran Tutoring services, at lowest cost possible."],"URL":"www.hnquranacademy.co.uk","PictureCount":1,"PictureFolderName":"HNQ"}';
Projects[6] = '{"Project_Name":"Business Intelligence","Duration":"3 Months","Technology":"Asp.net , C#, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["This application design and develop for marketing & sales system","This Application provide rate information","This application provide weather information ","This Application provide custom data information ","This application trigger for events","Also the purpose of this application analytics reports","Shows business information also shows banks details","Shows profile wealth and income details","Shows profile of assets age","Shows report assets allocation date"],"URL":"dashboarddesign.nomansadiq.pk","PictureCount":8,"PictureFolderName":"BI"}';
Projects[7] = '{"Project_Name":"Accounts Receivable","Duration":"1 Month","Technology":"ASP.NET MVC , C#, Entity Framework, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["Purpose of this application to enhance the business scalability","Track the payments those are overdue within 2 days","Track the payments those are overdue within 15 days","Send email reminder to customer for overdue payments","Track the total number of reminders, sent to customer"],"URL":"","PictureCount":4,"PictureFolderName":"AR"}';
Projects[8] = '{"Project_Name":"Car Dealers","Duration":"1 Month","Technology":"ASP.NET MVC , C#, Entity Framework, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["The purpose of this application to manage the dealer","Add information for new dealers","Reporting services on dealer","Provided registration form for dealer","Provide interface to add their credit card information for future selling and purchasing"],"URL":"","PictureCount":3,"PictureFolderName":"Car_Dealers"}';
Projects[9] = '{"Project_Name":"London Massage Care","Duration":"1 Month","Technology":"ASP.NET MVC , C#, Entity Framework, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["Massage service in London that provides you with a wide variety of therapeutic massages","By booking a massage online at the London Massage Care, you save time and get to experience the same spa feel at your home, office or hotel.","Order a massage of your liking any day, selecting your favourite massage therapist and experience the ultimate relaxation"],"URL":"","PictureCount":10,"PictureFolderName":"LMC"}';
Projects[10] = '{"Project_Name":"Survey Builder","Duration":"6 Months","Technology":"Asp.net , C#, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["This survey system can also allow printing whole survey in plain paper.","This survey builder also allows to anyone to conduct a survey anywhere.","This system will also provide interface to print and save conducted survey for future consideration."],"URL":"","PictureCount":5,"PictureFolderName":"SB"}';
Projects[11] = '{"Project_Name":"Energy Consumption Calculator","Duration":"3 Months","Technology":"Asp.net , C#, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["This survey system can also allow printing whole survey in plain paper.","This survey builder also allows to anyone to conduct a survey anywhere.","This system will also provide interface to print and save conducted survey for future consideration."],"URL":"","PictureCount":4,"PictureFolderName":"ECC"}';
Projects[12] = '{"Project_Name":"Poultry Form System","Duration":"3 Months","Technology":" C#.NET, SQL Server 2008","Design":"Object Oriented","Description":["Keep employee information & Customer Information","Keep details of Income & expense","Generate Reports","Manage System user"],"URL":"","PictureCount":6,"PictureFolderName":"PFS"}';
Projects[13] = '{"Project_Name":"Newsletter Flyover","Duration":"3 Months","Technology":" C#.NET, SQL Server 2008","Design":"Object Oriented","Description":["This system provide facility to send email message also can send html template","This system provide facility to imports your contact (emails) 4 sources (MS Excel, MS Document, CVS, Notepad)","Generate Reports","Manage System user"],"URL":"","PictureCount":1,"PictureFolderName":"Newsletterflyover"}';
Projects[14] = '{"Project_Name":"Allah Hoo Mobile","Duration":"3 Months","Technology":" C#.NET, SQL Server 2008","Design":"Object Oriented","Description":["Keep track the all Products","Keep details of the Products Sales & Purchase","Generate Daily base Reports Sales & Purchase","Manage System user"],"URL":"","PictureCount":3,"PictureFolderName":"AH"}';
Projects[15] = '{"Project_Name":"Artificial Intelligent Viva Exam Scheduler","Duration":"1 Month","Technology":"ASP.NET, C#.NET, HTML, CSS, JavaScript, SQL Server 2008","Design":"Object Oriented","Description":["Student can reschedule their viva by sending request","Student can print their schedule","Generate Daily base Reports Sales & Purchase","Manage System user"],"URL":"","PictureCount":9,"PictureFolderName":"AIVES"}';
Projects[16] = '{"Project_Name":"Trip Advisor","Duration":"1 Month","Technology":"ASP.NET, VB.NET, HTML, CSS, JavaScript, SQL Server 2008","Design":"Object Oriented","Description":["User can search hotel and view their photos","User can view latest review","User can view top rating hotels","Manage System user"],"URL":"","PictureCount":5,"PictureFolderName":"TA"}';
Projects[17] = '{"Project_Name":"Business Automation","Duration":"3 Months","Technology":"ASP.NET MVC , C#, Entity Framework, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["This application specially design in window services which is running on the background of the machine","In this automation, system able to do automatically do all business automation requirements","Send daily invoices to www.xero.com (Integration with Xero)","Send daily payments details to www.xero.com (Integration with Xero)","Send daily report to Accounts officer for overdue payments","Send emails to customer about overdue invoices","Send monthly report of total no of (Breakage, Teamwork, Attendance, Complaint, Compliment, Protocol, Feedback and customer lost)"],"URL":"","PictureCount":1,"PictureFolderName":"BA"}';
Projects[18] = '{"Project_Name":"Xero Invoice Import System","Duration":"1 Month","Technology":"ASP.NET MVC , C#, Entity Framework, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["Xero Invoice Import system specially designed and developed for consuming the www.Xero.com APIs","Using this custom application, user of this application can view their invoices","Upload new invoices","View their customer’s details","As well all of the functionality available that xero offering through the APIs"],"URL":"","PictureCount":2,"PictureFolderName":"XPI"}';
Projects[19] = '{"Project_Name":"Market Line","Duration":"1 Month","Technology":"ASP.NET Web Forms , C#, HTML, CSS, JS, JQuery, Ajax, SQL Server 2008","Design":"Object Oriented","Description":["Keep the business information, selling and purchase the leaflets ","Track the staff ","Track the Companies ","Track the areas ","Generates the reports ","Export in PDF"],"URL":"","PictureCount":7,"PictureFolderName":"ML"}';

function getParameterByName(name) {
    name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
    var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
        results = regex.exec(location.search);
    return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
}

